Repository jellyfin/jellyfin-kodi, pull requests merged in 2022-10, with the labels that each got.

#661 CI - remove use_aliases from emoji command
  .github/tools/reformat_changelog.py
Labels: ci

#629 Add option to disable remote control
  jellyfin_kodi/jellyfin/ws_client.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.en_us/strings.po
  resources/settings.xml
Labels: enhancement

#684 Add back verify_kodi_defaults from #426
  jellyfin_kodi/entrypoint/service.py
  jellyfin_kodi/helper/xmls.py
Labels: bugfix

#687 Properly apply Movie premiered date
  .editorconfig
  jellyfin_kodi/objects/kodi/queries.py
  jellyfin_kodi/objects/movies.py
  jellyfin_kodi/objects/obj_map.json
Labels: bugfix
