Repository jellyfin/jellyfin-kodi, pull requests merged in 2024-08, with the labels that each got.

#895 Improve HEVC codec handling in transcoding profiles
  jellyfin_kodi/helper/playutils.py
  tests/test_playutils_settings.py
Labels: bugfix, tests

#892 Add AV1 as a preferred codec option
  jellyfin_kodi/helper/playutils.py
  resources/settings.xml
  tests/test_playutils_settings.py
Labels: enhancement

#902 Fix transcode settings visibility logic
  resources/settings.xml
Labels: bugfix

#903 Disable delete option in context menu by default
  resources/settings.xml
Labels: chore
