Repository jellyfin/jellyfin-kodi, pull requests merged in 2024-06, with the labels that each got.

#868 Add tool to run black on the whole project
  .github/tools/run_black.sh
Labels: build

#871 Clear playlist if clear flag is set (UpNext)
  jellyfin_kodi/objects/actions.py
Labels: bugfix

#874 Remove unused function compare_version
  jellyfin_kodi/helper/__init__.py
  jellyfin_kodi/helper/utils.py
Labels: cleanup

#873 Add pre-commit config
  .editorconfig
  .pre-commit-config.yaml
Labels: cleanup

#869 Run the black formatter
  .git-blame-ignore-revs
  build.py
  jellyfin_kodi/client.py
  jellyfin_kodi/connect.py
  jellyfin_kodi/database/__init__.py
  jellyfin_kodi/database/jellyfin_db.py
  jellyfin_kodi/database/queries.py
  jellyfin_kodi/dialogs/context.py
  jellyfin_kodi/dialogs/loginmanual.py
  jellyfin_kodi/dialogs/serverconnect.py
  jellyfin_kodi/dialogs/servermanual.py
  jellyfin_kodi/dialogs/usersconnect.py
  jellyfin_kodi/downloader.py
  jellyfin_kodi/entrypoint/context.py
  jellyfin_kodi/entrypoint/default.py
  jellyfin_kodi/entrypoint/service.py
  jellyfin_kodi/full_sync.py
  jellyfin_kodi/helper/api.py
  jellyfin_kodi/helper/exceptions.py
  jellyfin_kodi/helper/lazylogger.py
  jellyfin_kodi/helper/loghandler.py
  jellyfin_kodi/helper/playutils.py
  jellyfin_kodi/helper/translate.py
  jellyfin_kodi/helper/utils.py
  jellyfin_kodi/helper/wrapper.py
  jellyfin_kodi/helper/xmls.py
  jellyfin_kodi/jellyfin/__init__.py
  jellyfin_kodi/jellyfin/api.py
  jellyfin_kodi/jellyfin/client.py
  jellyfin_kodi/jellyfin/configuration.py
  jellyfin_kodi/jellyfin/connection_manager.py
  jellyfin_kodi/jellyfin/credentials.py
  jellyfin_kodi/jellyfin/http.py
  jellyfin_kodi/jellyfin/ws_client.py
  jellyfin_kodi/library.py
  jellyfin_kodi/monitor.py
  jellyfin_kodi/objects/actions.py
  jellyfin_kodi/objects/kodi/artwork.py
  jellyfin_kodi/objects/kodi/kodi.py
  jellyfin_kodi/objects/kodi/movies.py
  jellyfin_kodi/objects/kodi/music.py
  jellyfin_kodi/objects/kodi/queries.py
  jellyfin_kodi/objects/kodi/queries_music.py
  jellyfin_kodi/objects/movies.py
  jellyfin_kodi/objects/music.py
  jellyfin_kodi/objects/musicvideos.py
  jellyfin_kodi/objects/obj.py
  jellyfin_kodi/objects/tvshows.py
  jellyfin_kodi/objects/utils.py
  jellyfin_kodi/player.py
  jellyfin_kodi/views.py
  service.py
  tests/test_clean_none_dict_values.py
  tests/test_imports.py
  typings/jellyfin_kodi/database/jellyfin_db.pyi
Labels: cleanup

#875 Add black to CI, pre-commit and devcontainer
  .devcontainer/Python 3.11/devcontainer.json
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  .vscode/extensions.json
  requirements-dev.txt
Labels: ci

#877 Fix sonarcloud lint
  jellyfin_kodi/downloader.py
Labels: cleanup

#878 Editorconfig pre-commit and indentation adjustment
  .build/template.xml
  .editorconfig
  .git-blame-ignore-revs
  .github/issue_template.md
  .github/releasing.md
  .github/renovate.json
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  jellyfin_kodi/objects/obj.py
  resources/skins/default/1080i/script-jellyfin-context.xml
Labels: cleanup

#880 Remove dependency on six
  .pre-commit-config.yaml
  jellyfin_kodi/client.py
  jellyfin_kodi/connect.py
  jellyfin_kodi/database/__init__.py
  jellyfin_kodi/dialogs/context.py
  jellyfin_kodi/dialogs/loginmanual.py
  jellyfin_kodi/dialogs/resume.py
  jellyfin_kodi/dialogs/serverconnect.py
  jellyfin_kodi/dialogs/servermanual.py
  jellyfin_kodi/dialogs/usersconnect.py
  jellyfin_kodi/downloader.py
  jellyfin_kodi/entrypoint/context.py
  jellyfin_kodi/entrypoint/default.py
  jellyfin_kodi/entrypoint/service.py
  jellyfin_kodi/full_sync.py
  jellyfin_kodi/helper/loghandler.py
  jellyfin_kodi/helper/playutils.py
  jellyfin_kodi/helper/translate.py
  jellyfin_kodi/helper/utils.py
  jellyfin_kodi/helper/wrapper.py
  jellyfin_kodi/helper/xmls.py
  jellyfin_kodi/jellyfin/api.py
  jellyfin_kodi/jellyfin/http.py
  jellyfin_kodi/jellyfin/utils.py
  jellyfin_kodi/jellyfin/ws_client.py
  jellyfin_kodi/library.py
  jellyfin_kodi/monitor.py
  jellyfin_kodi/objects/actions.py
  jellyfin_kodi/objects/movies.py
  jellyfin_kodi/objects/musicvideos.py
  jellyfin_kodi/objects/obj.py
  jellyfin_kodi/objects/tvshows.py
  jellyfin_kodi/player.py
  jellyfin_kodi/views.py
  release.yaml
  requirements-dev.txt
  service.py
Labels: cleanup, python2
