Repository jellyfin/jellyfin-kodi, pull requests merged in 2024-02, with the labels that each got.

#816 Remove Python 2 support 🔥
  .devcontainer/Python 2.7/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: major

#791 Fix uncaught exception in Player.report_playback()
  jellyfin_kodi/player.py
Labels: bugfix

#820 Remove py2 specific dependencies
  release.yaml
  requirements-dev.txt
Labels: cleanup, python2

#774 Fix syncing of mixed TV libraries
  jellyfin_kodi/helper/utils.py
Labels: bugfix, mixed library
