Repository jellyfin/jellyfin-kodi, pull requests merged in 2024-03, with the labels that each got.

#831 Quick and dirty movie_view fix.
  jellyfin_kodi/objects/kodi/movies.py
  jellyfin_kodi/objects/kodi/queries.py
  jellyfin_kodi/objects/movies.py
Labels: bugfix, Kodi 21

#803 Use xbmcvfs functions to read and write filesystem files
  jellyfin_kodi/helper/xmls.py
Labels: bugfix, apple

#834 Add automatic database migration for Kodi Omega
  jellyfin_kodi/library.py
  jellyfin_kodi/objects/kodi/movies.py
  jellyfin_kodi/objects/kodi/queries.py
Labels: bugfix, Kodi 21

#812 Fix websocket automatic reconnection
  jellyfin_kodi/jellyfin/ws_client.py
  release.yaml
  requirements-dev.txt
Labels: bugfix

#804 Pass HDR library metadata to kodi to display logos
  jellyfin_kodi/helper/api.py
  jellyfin_kodi/objects/actions.py
  jellyfin_kodi/objects/kodi/queries.py
Labels: enhancement, ux

#731 Fix #539 "cast not available"
  jellyfin_kodi/database/jellyfin_db.py
  jellyfin_kodi/database/queries.py
  jellyfin_kodi/objects/kodi/kodi.py
  jellyfin_kodi/objects/kodi/queries.py
  jellyfin_kodi/objects/tvshows.py
Labels: enhancement, ux

#841 Use sudo for kodirepo command
  .github/workflows/publish.yaml
Labels: build, ci, bugfix
